### ISSUE TITLE
Remove compatibility stuff not required for `minVersion`

### ISSUE THREAD

**Issue by luke-** [humhub/updater#37]

**Comment by yurabakhtin** [comment]
@luke- Sorry, not clear, do you mean to remove code for old versions less current `"minVersion": "1.15"` like these? :

- https://github.com/humhub/updater/blob/master/Module.php#L47-L70
- https://github.com/humhub/updater/blob/master/libs/AvailableUpdate.php#L56-L66

**Comment by luke-** [comment]
@yurabakhtin Yes exactly, I was talking about removing these blocks.

But if the `minVersion` of the installer would be increased, it should not make any problem or did I missed something?

**Comment by yurabakhtin** [comment]
@luke- 

> But if the `minVersion` of the installer would be increased, it should not make any problem or did I missed something?

I thought if module has `"humhub": {"minVersion": "1.15"},` in config then this module cannot be installed and used with versions < `1.15`. But I have tested this case and don't see any restrictions for installing and using, is it ok or some bug?
If it is ok, then what reason to have the `minVersion`? I expected to get at aleast some warning before install a module on older core version, also it would be better to disable the module is it requires newer core version.

---

I am not sure to remove the compatibility stuff because I think it works like this:

- Current Humhub version is old where the class `humhub\libs\CURLHelper` or `yii\httpclient\Client` don't exist, (see here https://github.com/humhub/updater/issues/37#issuecomment-1665467621 where the classes are used).
- Run to download new package, so here we need the compatibility code, because new code is not downloaded yet.

**Comment by luke-** [comment]
@yurabakhtin The `minVersion` check currently only takes place on our Marketplace API. The API (`web` Project) only returns module versions that meet the min version requirement. 

I've created a new issue here: https://github.com/humhub/humhub-internal/issues/98

--- 

Hmm, I think it is safe to remove the compatibility layers in the updater module.
The Marketplace (API) always provides the appropriate Updater Module version for the current HumHub version.

**Comment by yurabakhtin** [comment]
@luke- Thanks for the info, ok if you think it is safe then I have done this in PR https://github.com/humhub/updater/pull/39.
