### ISSUE TITLE
`v2.1.x` throws error on HumHub 1.15+ 

### ISSUE THREAD

**Issue by luke-** [humhub/updater#42]
For a better update process, it would be good to release a version `2.1.13` of the updater module, which simply redirects to the marketplace instead of throwing an error on HumHub version `1.15`+.

![image](https://github.com/humhub/updater/assets/4736168/e46798ac-db55-4aa8-9cf0-1bbac096c047)

**Comment by dreua** [comment]
Does that mean that the updater is not needed for those humhub versions?

**Comment by luke-** [comment]
@dreua The update itself is working, Just an error after the successful update.

**Comment by yurabakhtin** [comment]
@luke- I have created the changes in the branch https://github.com/humhub/updater/tree/fix/42-redirect-to-marketplace, but we should not create PR because we don't need to merge it to `master` branch.

I think we should create a new release `2.1.13` directly from the branch `fix/42-redirect-to-marketplace`, right?

Commit https://github.com/humhub/updater/commit/ef63a45424806dc0d3667da73a9a46a879140b24 - please note I have updated min version to `1.4` because I find the controller `protected/humhub/modules/marketplace/controllers/BrowseController.php` was added here https://github.com/humhub/humhub/commit/4ba5bcbf8cd46542f51ed805f7b3d90828048462#diff-f62e14ddc993740cf1de865bc72775676a84d8d70b56f1261f42f585acd95cd5,
I guess it was done in version `1.3.14  (June 26, 2019)` or later.
